global:
  prefix: "&8[&bGotta&6Gras&8] &f"
  join-messages:
    welcome: "&6Bienvenue &e{player} &6sur le lobby GottaGras!"
    leave: "&e{player} &6a quitté le lobby."
  spawn:
    world: "world"
    x: 0.5
    y: 256.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0

protection:
  messages:
    deny-break: "&6Protection &8» &eDésolé, tu ne peux pas modifier le lobby."
    deny-place: "&6Protection &8» &eLa construction est interdite ici."
    deny-drop: "&6Protection &8» &eTu ne peux pas jeter d'objets ici."

selector:
  item:
    material: "COMPASS"
    name: "&6Navigateur de jeux"
    slot: 4
    lore:
      - "&7Permet de naviguer entre"
      - "&7les différents serveurs."
      - ""
      - "&eClic-droit pour ouvrir"
  games:
    - name: "&aBingo"
      icon: "PAPER"
      server: "bingo"
      slot: 7
      lore:
        - "&7Complète ta grille d'objets"
        - "&7le plus vite possible !"
        - ""
        - "&e▶ Clique pour rejoindre"

    - name: "&bFallen Kingdom"
      icon: "IRON_SWORD"
      server: "fk"
      slot: 5
      lore:
        - "&7Défends ta salle des coffres"
        - "&7et assaille les bases adverses."
        - ""
        - "&e▶ Clique pour conquérir"

    - name: "&cUHC"
      icon: "GOLDEN_APPLE"
      server: "uhc"
      slot: 3
      lore:
        - "&7Pas de régénération naturelle."
        - "&7Seul le dernier survivant gagne."
        - ""
        - "&e▶ Clique pour combattre"

    - name: "&dCité"
      icon: "BRICK"
      server: "cite"
      slot: 1
      lore:
        - "&7Amasse des émeraudes et"
        - "&7achète les quartiers de la ville."
        - ""
        - "&e▶ Clique pour t'enrichir"
