global:
  prefix: "&8[&bGotta&6Gras&8] &f"
  join-messages:
    welcome: "&6Bienvenue &e{player} &6sur le lobby GottaGras!"
    leave: "&e{player} &6a quitté le lobby."
  spawn:
    world: "world"
    x: 0.5
    y: 256.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0

protection:
  messages:
    deny-break: "&6Protection &8» &eDésolé, tu ne peux pas modifier le lobby."
    deny-place: "&6Protection &8» &eLa construction est interdite ici."
    deny-drop: "&6Protection &8» &eTu ne peux pas jeter d'objets ici."
